### ISSUE TITLE
Need to parse ALERT_SMS as a string then split

### ISSUE THREAD

**Issue by bdeanindy** [anilkumarbp/Message-Dispatcher#21]
The ALERT_SMS environment variable is currently listed in the template as an array, but if you use the array and have more than one element, the property returns as `undefined` and causes a parse error.

Would be best (since this is a limitation of the `dotenv` module) to just load a comma separated list of numbers and then use JS to split on the comma. This should solve that problem.

**Comment by anilkumarbp** [comment]
The ALERT_SMS.map function takes the array elements ( numbers )  specified as string.  Verfied, the functionality works for more than two numbers.
