### ISSUE TITLE
Missing sleep module in package.json

### ISSUE THREAD

**Issue by bdeanindy** [anilkumarbp/Message-Dispatcher#22]
The sleep module is used within `index.js` but it is not referenced in the `package.json` file.

Please run `npm install --save sleep` to ensure this module is written to the package file and usable by developers when they execute the `npm install` command.

**Comment by bdeanindy** [comment]
Actually, we only instantiate this variable...but I never see it being used in `index.js`.

@anilkumarbp is this what is expected?

**Comment by anilkumarbp** [comment]
sleep module was utilized as part of the testing purpose. But we would not need it now. Would remove the  variable and the dependency.

**Comment by bdeanindy** [comment]
I removed it as well. The dependency was only installed for you sir (since you didn't include it in the package.json or use `npm install --save <mod_name>` then it wasn't listed there and threw an error for me until I manually added it.
