### ISSUE TITLE
Console reporter to sysadmin has looping scope issues

### ISSUE THREAD

**Issue by bdeanindy** [anilkumarbp/Message-Dispatcher#23]
The following messages need to have the loops scoped within a closure to properly provide valid information:
1. "************\* Retreived  156  : devices so far ************"
   ^^^ Same ID keeps showing for all
2. "The Device : 15204835020 has no emergency address attached to it. Kindly Add the Emergency Address to it."
   ^^^ Same ID keeps showing for all

**Comment by anilkumarbp** [comment]
Updated.
