### ISSUE TITLE
Timer issue

### ISSUE THREAD

**Issue by bdeanindy** [anilkumarbp/Message-Dispatcher#4]
Per @anilkumarbp :
Line number 100 within my index.js where I am trying to re-call the async method to Active-call API but I get a timer._repeat error.

**Comment by bdeanindy** [comment]
Below is the error message being provided during operation. The issue doesn't appear to be with the timer, but the fact that `call` is not defined.

timers.js:270
    timer._repeat.call(this);
                 ^

TypeError: Cannot read property 'call' of undefined
    at wrapper [as _onTimeout](timers.js:270:18)
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by bdeanindy** [comment]
My previous thought of "call" being undefined was both correct and incorrect. The real problem is the fact that you're passing in the result of `activeCalls()` instead of the reference to the `activeCalls` function. This is because you are including the parenthesis erroneously.

Once you remove the parenthesis it no longer errors. I will submit the PR now.

**Comment by anilkumarbp** [comment]
Fixed.
